### ISSUE TITLE
clm5nl-gen error

### ISSUE THREAD

**Issue by kongdd** [HPSCTerrSys/eCLM#11]
I am using the eCLM docker image. The example in eCLM has the following error. 
Any idea how to fix this problem?

```bash
docker run -it --rm -e "TERM=xterm-256color" \
    -v ${PWD}:/home/clmuser/eclm \
    -v /media/kong/Document/1x1_wuestebach:/home/clmuser/eclm/1x1_wuestebach \
    hpscterrsys/eclm bash

cd 1x1_wuestebach
export DATA_DIR="$(pwd)"
clm5nl-gen wtb_1x1.toml
```

```bash
Reading model parameters file from /home/clmuser/eclm/1x1_wuestebach/wtb_1x1.toml
Namelists will be saved to /home/clmuser/eclm/1x1_wuestebach
--> Generated drv_in
Traceback (most recent call last):
  File "/home/clmuser/.local/bin/clm5nl-gen", line 121, in <module>
    err_code = generate_namelists(params_file, out_dir)
  File "/home/clmuser/.local/bin/clm5nl-gen", line 69, in generate_namelists
    success, msg = build_namelist(nl, opts, out_dir)
  File "/home/clmuser/.local/lib/python3.9/site-packages/clm5nl/generators/__init__.py", line 26, in build_namelist
    success, status_msg = build_lnd_in(opts, out_file)   
  File "/home/clmuser/.local/lib/python3.9/site-packages/clm5nl/generators/gen_lnd_in.py", line 63, in build_lnd_in
    process_namelist_inline_logic()                # rest of namelist parameters
  File "/home/clmuser/.local/lib/python3.9/site-packages/clm5nl/generators/gen_lnd_in.py", line 142, in process_namelist_inline_logic
    setup_logic_delta_time()
  File "/home/clmuser/.local/lib/python3.9/site-packages/clm5nl/generators/gen_lnd_in.py", line 444, in setup_logic_delta_time
    error("can NOT set both -l_ncpl option (via LND_NCPL env variable) AND dtime namelist variable.")
  File "/home/clmuser/.local/lib/python3.9/site-packages/clm5nl/generators/gen_lnd_in.py", line 130, in error
    raise ValueError(msg)
ValueError: can NOT set both -l_ncpl option (via LND_NCPL env variable) AND dtime namelist variable.
```

**Comment by kongdd** [comment]
Thank u. I will have a try. Thanks for your awesome work.
