### ISSUE TITLE
Error running namelist generator of sample test case

### ISSUE THREAD

**Issue by AdrienDams** [HPSCTerrSys/eCLM#14]
Hi,

After installing eCLM on Levante (DKRZ), I am trying to run the sample test case. Here is the error message I have for the namelist generator:

```
(myenv) [a271098@levante3 1x1_wuestebach]$ export DATA_DIR="$(pwd)"
(myenv) [a271098@levante3 1x1_wuestebach]$ ../namelist_generator/clm5nl-gen wtb_1x1.toml 
Reading model parameters file from /work/aa0049/a271098_tmp/eCLM/1x1_wuestebach/wtb_1x1.toml
Namelists will be saved to /work/aa0049/a271098_tmp/eCLM/1x1_wuestebach
--> Generated drv_in
Traceback (most recent call last):
  File "/work/aa0049/a271098_tmp/eCLM/1x1_wuestebach/../namelist_generator/clm5nl-gen", line 121, in <module>
    err_code = generate_namelists(params_file, out_dir)
  File "/work/aa0049/a271098_tmp/eCLM/1x1_wuestebach/../namelist_generator/clm5nl-gen", line 69, in generate_namelists
    success, msg = build_namelist(nl, opts, out_dir)
  File "/work/aa0049/a271098_tmp/eCLM/namelist_generator/clm5nl/generators/__init__.py", line 26, in build_namelist
    success, status_msg = build_lnd_in(opts, out_file)   
  File "/work/aa0049/a271098_tmp/eCLM/namelist_generator/clm5nl/generators/gen_lnd_in.py", line 63, in build_lnd_in
    process_namelist_inline_logic()                # rest of namelist parameters
  File "/work/aa0049/a271098_tmp/eCLM/namelist_generator/clm5nl/generators/gen_lnd_in.py", line 142, in process_namelist_inline_logic
    setup_logic_delta_time()
  File "/work/aa0049/a271098_tmp/eCLM/namelist_generator/clm5nl/generators/gen_lnd_in.py", line 444, in setup_logic_delta_time
    error("can NOT set both -l_ncpl option (via LND_NCPL env variable) AND dtime namelist variable.")
  File "/work/aa0049/a271098_tmp/eCLM/namelist_generator/clm5nl/generators/gen_lnd_in.py", line 130, in error
    raise ValueError(msg)
ValueError: can NOT set both -l_ncpl option (via LND_NCPL env variable) AND dtime namelist variable.
(myenv) [a271098@levante3 1x1_wuestebach]$ 
```

Any idea what I can do?

Thanks

**Comment by AdrienDams** [comment]
see #11
